language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - kalakris-cmake
    packages:
    - gcc-5
    - g++-5
    - cmake

env: COMPILER=g++-5

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt4-dev-tools cppcheck

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..

script: 
  - make
  - cppcheck -f -q  --enable=all --std=c++11 ..
